### ISSUE TITLE
Problema g%ss

### ISSUE THREAD

**Issue by umadollie** [AndreMor8/gidget#253]
El comando g%ss fue revisado y puede de alguna forma mostrar contenido NSFW en canales SFW. Por ejemplo con el dominio pornoxd.com (sugerido por un moderador de DT). Recomendaría agregar más dominios o filtros, lindo resto de día, querido.

**Comment by AndreMor8** [comment]
Hola!

El bot hace lo posible para detectar NSFW en las imágenes que se mandan por g%ss, e intento añadir páginas nuevas para cuando el detector automático con IA no pueda hacer nada. Es responsabilidad de los moderadores de cada servidor el educar a sus miembros de no usar el comando para mostrar NSFW.

Añadi la página que pidió, gracias por contribuir.

Espero se encuentre bien :)
